version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - simple
    restart: always

  simple:
    build: ./simple-server/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: always
